#!/usr/bin/python
import re
import sqlite3
import sys
from pathlib import Path

db_path = Path(sys.argv[1])
measurement_name = sys.argv[2]
output_file_arg = sys.argv[3]

if output_file_arg:
    out_path = Path(output_file_arg)
else:
    safe_name = re.sub(r"[^A-Za-z0-9._-]+", "_", measurement_name).strip("_") or "measurement"
    out_path = Path.cwd() / f"{safe_name}.sql"


def sql_literal(value):
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return repr(value)
    escaped = str(value).replace("'", "''")
    return f"'{escaped}'"


def insert_lines(table_name, columns, rows):
    lines = []
    col_sql = ", ".join(columns)
    for row in rows:
        values_sql = ", ".join(sql_literal(row[column]) for column in columns)
        lines.append(f"INSERT INTO {table_name} ({col_sql}) VALUES ({values_sql});")
    return lines


conn = sqlite3.connect(db_path)
conn.row_factory = sqlite3.Row
cur = conn.cursor()

measurements = cur.execute(
    "SELECT * FROM measurements WHERE name = ? ORDER BY id", (measurement_name,)
).fetchall()
if not measurements:
    print(f"error: no measurement found with name '{measurement_name}'", file=sys.stderr)
    sys.exit(1)

measurement_ids = [row["id"] for row in measurements]
id_placeholders = ",".join("?" for _ in measurement_ids)

program_measurements = cur.execute(
    f"SELECT * FROM program_measurements WHERE measurement_id IN ({id_placeholders}) ORDER BY id",
    measurement_ids,
).fetchall()

program_ids = sorted({row["program_id"] for row in program_measurements})
programs = []
if program_ids:
    placeholders = ",".join("?" for _ in program_ids)
    programs = cur.execute(
        f"SELECT * FROM programs WHERE id IN ({placeholders}) ORDER BY id", program_ids
    ).fetchall()

program_measurement_ids = [row["id"] for row in program_measurements]
test_results = []
benchmark_runs = []
if program_measurement_ids:
    placeholders = ",".join("?" for _ in program_measurement_ids)
    test_results = cur.execute(
        f"SELECT * FROM test_results WHERE program_measurement_id IN ({placeholders}) ORDER BY id",
        program_measurement_ids,
    ).fetchall()
    benchmark_runs = cur.execute(
        f"SELECT * FROM benchmark_runs WHERE program_measurement_id IN ({placeholders}) ORDER BY id",
        program_measurement_ids,
    ).fetchall()

lines = [
    "-- Export generated by export_measurement.sh",
    "BEGIN;",
]
lines.extend(insert_lines("programs", ["id", "name"], programs))
lines.extend(
    insert_lines(
        "measurements",
        ["id",
         "name",
         "started_at",
         "c_compiler_cmd",
         "cpp_compiler_cmd",
         "opt_cmd",
         "embedding_cmd",
         "compile_cmd",
         "tests_executed",
         "benchmarks_executed",
         "baseline_id"],
        measurements,
    )
)
lines.extend(
    insert_lines(
        "program_measurements",
        ["id", "measurement_id", "program_id", "embedding_log", "watermarks_added", "binary_size_bytes"],
        program_measurements,
    )
)
lines.extend(insert_lines("test_results", ["id", "program_measurement_id", "passed"], test_results))
lines.extend(
    insert_lines(
        "benchmark_runs",
        ["id", "program_measurement_id", "iteration", "runtime_seconds"],
        benchmark_runs,
    )
)
lines.append("COMMIT;")
lines.append("")

out_path.write_text("\n".join(lines), encoding="utf-8")
print(f"Exported {len(measurements)} measurement(s) to {out_path}")
conn.close()
